# Generated by Django 3.1.6 on 2021-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210224_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='year_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='director',
            name='year_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(verbose_name='World premiere date'),
        ),
        migrations.AlterField(
            model_name='music',
            name='year_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='year_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
