# Generated by Django 3.1.6 on 2021-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210224_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='title', max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
